### ISSUE TITLE
Add Docker config option under Deployment 

### ISSUE THREAD

**Issue by sahat** [sahat/megaboilerplate#93]
Add ability to generate Docker config files.

**Comment by MikeMichel** [comment]
argh, just finished the second blog post about the "old" hackathon-starter. however, megaboilerpalte looks awesome. The dev docker-compose.yml i created still works with the express+mongodb+jade combi.

```
version: '2'
services:

  web:
    image: node:6.1
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm install -g nodemon ; nodemon -e js,jade app.js'
    ports:
      - "80:3000"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB: "mongodb://mongo:27017/hackathon"

  mongo:
    image: mongo:3
    command: mongod --smallfiles
    networks:
      - all

networks:
  all:
```

same for the Dockerfile:

```
FROM node:6.1.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app/
RUN npm install

CMD [ "node", "app.js" ]
```

What do you have in mind? Generating only buildfiles regarding the choosed frameworks or docker-compose.yml files too?

btw. in hackathon-starter you switched from MONGODB to MONGODB_URI


cheers,

mike
